# HelpGUI
# Please report bugs here: https://github.com/Ziomkeee/HelpGUI/issues
# How to configure a plugin: https://github.com/Ziomkeee/HelpGUI/wiki

#Actions section
#Check https://github.com/Ziomkeee/HelpGUI/wiki/Actions
actions:
  open:
    permission: helpgui.open
    execute:
    - '%open%otherGUI'
  send:
    permission: helpgui.send
    execute:
    - '%send%Hey %player%!'
  executePlayer:
    permission: helpgui.execute
    execute:
    - '%cmd-player%msg %player% hey!'
  executeConsole:
    permission: helpgui.execute
    execute:
    - '%cmd-console%say Hey %player%!'
  teleport:
    permission: helpgui.teleport
    execute:
    - '%teleport%world:10:100:10'
  give:
    permission: helpgui.give
    execute:
    - '%give%stone:10'
  remove:
    permission: helpgui.remove
    execute:
    - '%remove%stone:10'
  close:
    permission: helpgui.close
    execute:
    - '%remove%stone:10'
    - '%close%'


#Command opening the main gui
cmd: "help"

#Language section
#%name% refers to the name of the GUI being loaded when the plugin is enabled / restarted
MSG:
  prefix: "&7[&6&lHelpGUI] "
  noperm: "&cYou don't have access to this action!"
  notexist: "&cThis GUI does not exist, please contact the administrator!"
  noitem: "&cYou do not have enough items!"
  actionnotexist: "&cThis actions does not exist, please contact the administrator!"
  load: "GUI %name% has been loaded"
  reload: "&aConfiguration reloaded!"